# Wirepas Oy 2018
---
- name: create composition file for {{wpe_version}}
  template:
   src: "docker-compose_wpe.j2"
   dest: "{{service_home}}/docker-compose.yml"
   mode: 0775

- name: create utility scripts
  template:
    src: "{{item}}.j2"
    dest: "{{service_home}}/{{item}}.sh"
    mode: 0775
  loop:
    - "redeploy"
    - "wpe_generate_certs"

- name: check that the databases.json exists
  stat:
    path: "{{service_home}}/databases.json"
  register: stat_result

- name: generate database configuration file
  template:
    src: "databases.j2"
    dest: "{{service_home}}/databases.json"
  ignore_errors: true
  when: not stat_result.stat.exists

- name: start Docker service
  shell: "cd {{service_home}} && ./redeploy.sh"
